
import { Finding } from "./vulnerability";
import fs from "fs";
import path from "path";

export class Reporter {
    async generateHTML(url: string, findings: Finding[]): Promise<string> {
        const timestamp = new Date().toISOString().split("T")[0];
        const safeUrl = url.replace(/[^a-zA-Z0-9]/g, "_");

        // Ensure reports directory exists
        const reportsDir = path.resolve(process.cwd(), "public/reports");
        if (!fs.existsSync(reportsDir)) {
            fs.mkdirSync(reportsDir, { recursive: true });
        }

        const filename = `scan_${safeUrl}_${timestamp}.html`;
        const filepath = path.join(reportsDir, filename);

        const highCount = findings.filter(f => f.severity === 'high' || f.severity === 'critical').length;
        const mediumCount = findings.filter(f => f.severity === 'medium').length;
        const lowCount = findings.filter(f => f.severity === 'low' || f.severity === 'info').length;

        const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Security Scan Report - ${url}</title>
    <style>
        body { font-family: 'Inter', sans-serif; background: #0f172a; color: #e2e8f0; margin: 0; padding: 40px; }
        h1, h2, h3 { color: #f8fafc; }
        .container { max-width: 900px; margin: 0 auto; }
        .header { text-align: center; border-bottom: 2px solid #334155; padding-bottom: 20px; margin-bottom: 40px; }
        .stats { display: flex; justify-content: space-around; background: #1e293b; padding: 20px; border-radius: 12px; margin-bottom: 40px; }
        .stat-box { text-align: center; }
        .stat-value { font-size: 2rem; font-weight: bold; }
        .high { color: #ef4444; }
        .medium { color: #f59e0b; }
        .low { color: #3b82f6; }
        .finding-card { background: #1e293b; border-left: 5px solid #64748b; padding: 20px; margin-bottom: 20px; border-radius: 8px; }
        .finding-card.critical { border-left-color: #ef4444; }
        .finding-card.high { border-left-color: #ef4444; }
        .finding-card.medium { border-left-color: #f59e0b; }
        .finding-card.low { border-left-color: #3b82f6; }
        .details { background: #0f172a; padding: 10px; border-radius: 4px; font-family: monospace; font-size: 0.9rem; margin-top: 10px; }
        .footer { text-align: center; color: #64748b; margin-top: 60px; font-size: 0.8rem; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Web Vulnerability Scan Report</h1>
            <p>Target: <strong>${url}</strong></p>
            <p>Date: ${new Date().toLocaleString()}</p>
        </div>

        <div class="stats">
            <div class="stat-box">
                <div class="stat-value high">${highCount}</div>
                <div>Critical / High</div>
            </div>
            <div class="stat-box">
                <div class="stat-value medium">${mediumCount}</div>
                <div>Medium</div>
            </div>
            <div class="stat-box">
                <div class="stat-value low">${lowCount}</div>
                <div>Low / Info</div>
            </div>
        </div>

        <h2>Detailed Findings</h2>
        ${findings.length === 0 ? "<p>No vulnerabilities found.</p>" : findings.map(f => `
            <div class="finding-card ${f.severity}">
                <h3>[${f.severity.toUpperCase()}] ${f.vulnerability}</h3>
                <p><strong>Location:</strong> ${f.location}</p>
                <div class="details">${f.details}</div>
            </div>
        `).join('')}

        <div class="footer">
            Generated by Krpterisio: Deep Techno Forensic Engine v1.0<br>
            KRPTERISIO | Project by Team Krpterisio
        </div>
    </div>
</body>
</html>
        `;

        fs.writeFileSync(filepath, html);
        return `/reports/${filename}`; // Return relative path for frontend link
    }
}
